[package]
name = "chip8"
version = "0.1.0"
authors = ["mike stedman <barbeque@users.noreply.github.com>"]

[dependencies]
rand = "*"

[features]
default = []

[dependencies.sdl2]
version = "0.31"
features = ["use_mac_framework"]
